project_id = "txiqrzitezigjxxjeoss"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[auth]
site_url = "http://localhost:3000"

[functions]
# No specific config needed for now
